const SUPABASE_URL = 'https://hnkqsxzzdhbmqnwvslpi.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhua3FzeHp6ZGhibXFud3ZzbHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2Mzc1NjgsImV4cCI6MjA4OTIxMzU2OH0.9ck9UdCnHD5tcK6VTbyHm_r7Z3yaKdnfGDYdcf5uFSc';
